/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import javax.swing.ComboBoxModel;

/**
 *
 * @author Dina
 */
public class CridetCard extends javax.swing.JFrame {

    /**
     * Creates new form CridetCard
     */
    public CridetCard() {
        initComponents();
        GUIManager.Instance().setDynamicSize(this, jPanel1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        SUbTitle = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        QustionMark = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        CardNumber = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        Subtitle5 = new javax.swing.JLabel();
        Subtitle6 = new javax.swing.JLabel();
        CVV = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        Subtitle7 = new javax.swing.JLabel();
        Name = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        Subtitle8 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        MM = new javax.swing.JComboBox<>();
        YY = new javax.swing.JComboBox<>();
        Error = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setPreferredSize(new java.awt.Dimension(1000, 820));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SUbTitle.setFont(new java.awt.Font("Cantarell Extra Bold", 0, 36)); // NOI18N
        SUbTitle.setForeground(new java.awt.Color(153, 153, 153));
        SUbTitle.setText("Credit Card");
        SUbTitle.setIconTextGap(15);
        jPanel1.add(SUbTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, 330, 50));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Icons/Payment Selection/Back.png"))); // NOI18N
        jButton3.setBorder(null);
        jButton3.setContentAreaFilled(false);
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 50, 60));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Icons/Payment Selection/Paynow.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setContentAreaFilled(false);
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 730, 320, 80));

        jSeparator2.setBackground(new java.awt.Color(160, 160, 160));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 920, 40));

        QustionMark.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Icons/Payment Selection/QM.png"))); // NOI18N
        QustionMark.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                QustionMarkMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                QustionMarkMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                QustionMarkMouseExited(evt);
            }
        });
        jPanel1.add(QustionMark, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 440, -1, 20));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Icons/Payment Selection/Visa.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 260, -1, -1));

        CardNumber.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        CardNumber.setForeground(new java.awt.Color(153, 153, 153));
        CardNumber.setText("6521  •••• •••• ••••");
        CardNumber.setBorder(null);
        CardNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CardNumberActionPerformed(evt);
            }
        });
        jPanel1.add(CardNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 260, 550, -1));

        jSeparator1.setBackground(new java.awt.Color(160, 160, 160));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 290, 390, 20));

        Subtitle5.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        Subtitle5.setForeground(new java.awt.Color(153, 153, 153));
        Subtitle5.setText("Credit Card Number");
        jPanel1.add(Subtitle5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 210, 280, 60));

        Subtitle6.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        Subtitle6.setForeground(new java.awt.Color(153, 153, 153));
        Subtitle6.setText("CVV");
        jPanel1.add(Subtitle6, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 420, 280, 60));

        CVV.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        CVV.setForeground(new java.awt.Color(153, 153, 153));
        CVV.setText("•••");
        CVV.setBorder(null);
        CVV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CVVActionPerformed(evt);
            }
        });
        jPanel1.add(CVV, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 470, 550, -1));

        jSeparator3.setBackground(new java.awt.Color(160, 160, 160));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 500, 130, 20));

        Subtitle7.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        Subtitle7.setForeground(new java.awt.Color(153, 153, 153));
        Subtitle7.setText("Card Holder Name");
        jPanel1.add(Subtitle7, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 520, 280, 60));

        Name.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        Name.setForeground(new java.awt.Color(153, 153, 153));
        Name.setText("Alex Turner");
        Name.setBorder(null);
        Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameActionPerformed(evt);
            }
        });
        jPanel1.add(Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 570, 550, -1));

        jSeparator4.setBackground(new java.awt.Color(160, 160, 160));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 600, 390, 20));

        Subtitle8.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        Subtitle8.setForeground(new java.awt.Color(153, 153, 153));
        Subtitle8.setText("Exp. Date");
        jPanel1.add(Subtitle8, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 320, 280, 60));

        jSeparator5.setBackground(new java.awt.Color(160, 160, 160));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 400, 50, 20));

        jSeparator6.setBackground(new java.awt.Color(160, 160, 160));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 400, 50, 20));

        MM.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MM", "Jan", "Feb", "Mar", "Apr", "May", "June", "July", "Aug", "Sep", "Oct", "Nov", "Dec", " " }));
        MM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MMActionPerformed(evt);
            }
        });
        jPanel1.add(MM, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 370, -1, -1));

        YY.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "YY", "22", "23", "24", "25", "26" }));
        YY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                YYActionPerformed(evt);
            }
        });
        jPanel1.add(YY, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 370, -1, -1));
        jPanel1.add(Error, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 630, 300, 60));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Signing/Rectangle 3 (1).png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 820));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 832, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void CardNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CardNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CardNumberActionPerformed

    private void CVVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CVVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CVVActionPerformed

    private void NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameActionPerformed

    private void YYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_YYActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_YYActionPerformed

    private void MMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MMActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
      Backend.CreditCardPaymentPage.Instance().payNowButtom
        (       this, 
                new Explore(),
                Backend.CreditCardPaymentPage.Instance().noEmptyCell(CardNumber,CVV,Name,Error,MM,YY));
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
         Backend.CreditCardPaymentPage.Instance().backButtom(this,new PaymentSelection());
    }//GEN-LAST:event_jButton3MouseClicked

    private void QustionMarkMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_QustionMarkMouseEntered
        // TODO add your handling code here:
        Backend.CreditCardPaymentPage.Instance().questionMarkIconMouseEntered(QustionMark);
        
    }//GEN-LAST:event_QustionMarkMouseEntered

    private void QustionMarkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_QustionMarkMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_QustionMarkMouseClicked

    private void QustionMarkMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_QustionMarkMouseExited
        // TODO add your handling code here:
        Backend.CreditCardPaymentPage.Instance().questionMarkIconMouseExited(QustionMark);
    }//GEN-LAST:event_QustionMarkMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CridetCard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CridetCard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CridetCard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CridetCard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CridetCard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CVV;
    private javax.swing.JTextField CardNumber;
    private javax.swing.JLabel Error;
    private javax.swing.JComboBox<String> MM;
    private javax.swing.JTextField Name;
    private javax.swing.JLabel QustionMark;
    private javax.swing.JLabel SUbTitle;
    private javax.swing.JLabel Subtitle5;
    private javax.swing.JLabel Subtitle6;
    private javax.swing.JLabel Subtitle7;
    private javax.swing.JLabel Subtitle8;
    private javax.swing.JComboBox<String> YY;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    // End of variables declaration//GEN-END:variables
}
