/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import java.awt.Point;
import java.awt.Rectangle;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author bethoveen
 */
public class Details extends javax.swing.JFrame {

    /**
     * Creates new form SignUpForm
     */
    public Details() {
        initComponents();
        GUIManager.Instance().setDynamicSize(this,jPanel1); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Container = new javax.swing.JPanel();
        OverView = new javax.swing.JButton();
        Title0 = new javax.swing.JLabel();
        Title1 = new javax.swing.JLabel();
        Info1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        Title2 = new javax.swing.JLabel();
        Info2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        Title3 = new javax.swing.JLabel();
        Info3 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        Title4 = new javax.swing.JLabel();
        Info4 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        FrontPanel = new javax.swing.JLabel();
        ButtonText = new javax.swing.JLabel();
        BigImage = new javax.swing.JLabel();
        BKG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1080, 920));
        setUndecorated(true);
        setSize(new java.awt.Dimension(1100, 1300));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Container.setBackground(new java.awt.Color(255, 255, 255));
        Container.setOpaque(false);
        Container.setLayout(null);

        OverView.setBackground(new java.awt.Color(255, 255, 255));
        OverView.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/DetailsIcons/Button (1).png"))); // NOI18N
        OverView.setBorder(null);
        OverView.setContentAreaFilled(false);
        OverView.setFocusCycleRoot(true);
        OverView.setMultiClickThreshhold(1L);
        OverView.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OverViewMouseClicked(evt);
            }
        });
        Container.add(OverView);
        OverView.setBounds(400, 0, 170, 70);

        Title0.setFont(new java.awt.Font("Cantarell", 0, 24)); // NOI18N
        Title0.setForeground(new java.awt.Color(102, 102, 102));
        Title0.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Title0.setText("Title");
        Container.add(Title0);
        Title0.setBounds(380, 50, 200, 40);

        Title1.setFont(new java.awt.Font("Cantarell", 0, 24)); // NOI18N
        Title1.setForeground(new java.awt.Color(102, 102, 102));
        Title1.setText("Artist :");
        Container.add(Title1);
        Title1.setBounds(60, 100, 80, 40);

        Info1.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        Info1.setForeground(new java.awt.Color(0, 0, 0));
        Info1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Info1.setText("dsadashdhashdhu  hfadsh asd kuayeguwi gfu weuygf yuqewgf uygwequ fy wgfey yuqwegf uygwef yugweuf");
        Info1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        Info1.setAutoscrolls(true);
        Info1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        Container.add(Info1);
        Info1.setBounds(60, 140, 850, 40);

        jSeparator1.setForeground(new java.awt.Color(102, 102, 102));
        Container.add(jSeparator1);
        jSeparator1.setBounds(160, 190, 620, 10);

        Title2.setFont(new java.awt.Font("Cantarell", 0, 24)); // NOI18N
        Title2.setForeground(new java.awt.Color(102, 102, 102));
        Title2.setText("Artist :");
        Container.add(Title2);
        Title2.setBounds(50, 210, 80, 40);

        Info2.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        Info2.setForeground(new java.awt.Color(0, 0, 0));
        Info2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Info2.setText("dsadashdhashdhu  hfadsh asd kuayeguwi gfu weuygf yuqewgf uygwequ fy wgfey yuqwegf uygwef yugweuf");
        Info2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        Info2.setAutoscrolls(true);
        Info2.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        Container.add(Info2);
        Info2.setBounds(50, 250, 850, 40);

        jSeparator2.setForeground(new java.awt.Color(102, 102, 102));
        Container.add(jSeparator2);
        jSeparator2.setBounds(150, 300, 620, 10);

        Title3.setFont(new java.awt.Font("Cantarell", 0, 24)); // NOI18N
        Title3.setForeground(new java.awt.Color(102, 102, 102));
        Title3.setText("Artist :");
        Container.add(Title3);
        Title3.setBounds(50, 320, 80, 40);

        Info3.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        Info3.setForeground(new java.awt.Color(0, 0, 0));
        Info3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Info3.setText("dsadashdhashdhu  hfadsh asd kuayeguwi gfu weuygf yuqewgf uygwequ fy wgfey yuqwegf uygwef yugweuf");
        Info3.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        Info3.setAutoscrolls(true);
        Info3.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        Container.add(Info3);
        Info3.setBounds(50, 360, 850, 40);

        jSeparator3.setForeground(new java.awt.Color(102, 102, 102));
        Container.add(jSeparator3);
        jSeparator3.setBounds(150, 410, 620, 10);

        Title4.setFont(new java.awt.Font("Cantarell", 0, 24)); // NOI18N
        Title4.setForeground(new java.awt.Color(102, 102, 102));
        Title4.setText("Artist :");
        Container.add(Title4);
        Title4.setBounds(50, 430, 80, 40);

        Info4.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        Info4.setForeground(new java.awt.Color(0, 0, 0));
        Info4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Info4.setText("dsadashdhashdhu  hfadsh asd kuayeguwi gfu weuygf yuqewgf uygwequ fy wgfey yuqwegf uygwef yugweuf");
        Info4.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        Info4.setAutoscrolls(true);
        Info4.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        Container.add(Info4);
        Info4.setBounds(50, 470, 850, 40);

        jSeparator4.setForeground(new java.awt.Color(102, 102, 102));
        Container.add(jSeparator4);
        jSeparator4.setBounds(150, 520, 620, 10);

        FrontPanel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/DetailsIcons/FrontPanel.png"))); // NOI18N
        Container.add(FrontPanel);
        FrontPanel.setBounds(0, 20, 940, 587);

        ButtonText.setText("jLabel1");
        Container.add(ButtonText);
        ButtonText.setBounds(50, 110, 130, 60);

        jPanel1.add(Container, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 720, 940, 610));

        BigImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/DetailsIcons/BigImage.png"))); // NOI18N
        jPanel1.add(BigImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 940, 820));

        BKG.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        BKG.setForeground(new java.awt.Color(153, 153, 153));
        BKG.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BKG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Signing/Rectangle 3 (1).png"))); // NOI18N
        jPanel1.add(BKG, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 940, 820));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 820, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OverViewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OverViewMouseClicked
        // TODO add your handling code here:
        System.out.println("Swiping");
        Point DefaultPosition = new Point(10,720);
        Point OpenedPosition = new Point(10,220);
        //Container.setLocation(DefaultPosition);
        GUIManager.Instance().SwipePanel(Container,DefaultPosition,OpenedPosition);
    }//GEN-LAST:event_OverViewMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Details().setVisible(true);
            }
        });
    }

            

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BKG;
    private javax.swing.JLabel BigImage;
    private javax.swing.JLabel ButtonText;
    private javax.swing.JPanel Container;
    private javax.swing.JLabel FrontPanel;
    private javax.swing.JLabel Info1;
    private javax.swing.JLabel Info2;
    private javax.swing.JLabel Info3;
    private javax.swing.JLabel Info4;
    private javax.swing.JButton OverView;
    private javax.swing.JLabel Title0;
    private javax.swing.JLabel Title1;
    private javax.swing.JLabel Title2;
    private javax.swing.JLabel Title3;
    private javax.swing.JLabel Title4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    // End of variables declaration//GEN-END:variables
}
