/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import javax.swing.JLabel;

/**
 *
 * @author Dina
 */
public class EventDetails extends javax.swing.JFrame {

    /**
     * Creates new form EventDetails
     */
    public EventDetails() {
        initComponents();
        GUIManager.Instance().setDynamicSize(this, jPanel1);
        JLabel[] Labels = new JLabel[]{ jLabel2,Subtitle2,time3,Date,details};
        Backend.EventDetailsPage.Instance().showEventDetails(Labels);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Subtitle7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        Subtitle2 = new javax.swing.JLabel();
        Subtitle3 = new javax.swing.JLabel();
        time3 = new javax.swing.JLabel();
        Subtitle4 = new javax.swing.JLabel();
        Date = new javax.swing.JLabel();
        details = new javax.swing.JLabel();
        Subtitle6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        Subtitle7.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        Subtitle7.setForeground(new java.awt.Color(153, 153, 153));
        Subtitle7.setText(".....");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setPreferredSize(new java.awt.Dimension(1000, 820));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator2.setBackground(new java.awt.Color(160, 160, 160));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 470, 820, 40));

        Subtitle2.setFont(new java.awt.Font("Calibri", 0, 30)); // NOI18N
        Subtitle2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Icons/Event Description/eye-of-ra 1.png"))); // NOI18N
        Subtitle2.setText(" Event Title");
        jPanel1.add(Subtitle2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 860, 60));

        Subtitle3.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        Subtitle3.setForeground(new java.awt.Color(153, 153, 153));
        Subtitle3.setText("Time");
        jPanel1.add(Subtitle3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 390, 200, 40));

        time3.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        time3.setText("10:39 - 1:00 pm");
        jPanel1.add(time3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 440, 170, -1));

        Subtitle4.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        Subtitle4.setForeground(new java.awt.Color(153, 153, 153));
        Subtitle4.setText("Date");
        jPanel1.add(Subtitle4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 380, 200, 60));

        Date.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        Date.setText("09/01/2022");
        jPanel1.add(Date, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 440, 110, -1));

        details.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        details.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        details.setText("detailssi nfooodddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd");
        details.setAutoscrolls(true);
        details.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(details, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 550, 770, 100));

        Subtitle6.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        Subtitle6.setForeground(new java.awt.Color(153, 153, 153));
        Subtitle6.setText("Details");
        jPanel1.add(Subtitle6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 490, 200, 60));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Icons/Event Description/Book.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 760, 170, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Icons/Event Description/BG1.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, 580));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Icons/Event Description/Back.png"))); // NOI18N
        jButton3.setBorder(null);
        jButton3.setContentAreaFilled(false);
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 50, 60));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Icons/Event Description/Bitmap.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 820, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
        Backend.BookingPage.Instance().backButtom(this, new Events() );
    }//GEN-LAST:event_jButton3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EventDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EventDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EventDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EventDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EventDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Date;
    private javax.swing.JLabel Subtitle2;
    private javax.swing.JLabel Subtitle3;
    private javax.swing.JLabel Subtitle4;
    private javax.swing.JLabel Subtitle6;
    private javax.swing.JLabel Subtitle7;
    private javax.swing.JLabel details;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel time3;
    // End of variables declaration//GEN-END:variables
}
