/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import javax.swing.JButton;

/**
 *
 * @author bethoveen
 */
public class Events extends javax.swing.JFrame {

    /**
     * Creates new form SignUpForm
     */
    public Events() {
        initComponents();
        GUIManager.Instance().setDynamicSize(this,jPanel1);
        Backend.EventsPage.Instance().CreateAllEvents(ButtonParent);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        SUbTitle = new javax.swing.JLabel();
        Back = new javax.swing.JButton();
        Search1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        ButtonParent = new javax.swing.JPanel();
        /*CustomButton = new javax.swing.JPanel();
        Title = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Image = new javax.swing.JLabel();
        CustomButton1 = new javax.swing.JPanel();
        Title1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Image1 = new javax.swing.JLabel();
        CustomButton2 = new javax.swing.JPanel();
        Title2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Image2 = new javax.swing.JLabel();
        CustomButton3 = new javax.swing.JPanel();
        Title3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Image3 = new javax.swing.JLabel();*/
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1080, 920));
        setUndecorated(true);
        setSize(new java.awt.Dimension(1100, 1300));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SUbTitle.setFont(new java.awt.Font("Cantarell Extra Bold", 0, 36)); // NOI18N
        SUbTitle.setForeground(new java.awt.Color(153, 153, 153));
        SUbTitle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Signing/pharaoh (1).png"))); // NOI18N
        SUbTitle.setText("Events");
        SUbTitle.setIconTextGap(15);
        jPanel1.add(SUbTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, 330, 50));

        Back.setBackground(new java.awt.Color(0, 0, 0));
        Back.setForeground(new java.awt.Color(0, 0, 0));
        Back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/folder/BackButton.png"))); // NOI18N
        Back.setBorder(null);
        Back.setBorderPainted(false);
        Back.setContentAreaFilled(false);
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        jPanel1.add(Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 50, 60));

        Search1.setBackground(new java.awt.Color(0, 0, 0));
        Search1.setForeground(new java.awt.Color(0, 0, 0));
        Search1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/folder/Search.png"))); // NOI18N
        Search1.setBorder(null);
        Search1.setBorderPainted(false);
        Search1.setContentAreaFilled(false);
        Search1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Search1ActionPerformed(evt);
            }
        });
        jPanel1.add(Search1, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 40, 50, 60));

        jTextField1.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(153, 153, 153));
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField1.setText("Search");
        jTextField1.setBorder(null);
        jTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField1FocusGained(evt);
            }
        });
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 50, 160, 40));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(null);
        jScrollPane1.setForeground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setAutoscrolls(true);
        jScrollPane1.setColumnHeaderView(null);
        jScrollPane1.setHorizontalScrollBar(null);
        jScrollPane1.setOpaque(false);

        ButtonParent.setBackground(new java.awt.Color(200, 200, 200));
        ButtonParent.setForeground(new java.awt.Color(255, 255, 255));
        ButtonParent.setDoubleBuffered(false);
        ButtonParent.setLayout(new java.awt.GridLayout(0, 1, 5, 5));
    

/*        CustomButton.setBackground(new java.awt.Color(255, 255, 255));
        CustomButton.setForeground(new java.awt.Color(255, 255, 255));
        CustomButton.setAlignmentX(1.0F);
        CustomButton.setAlignmentY(1.0F);
        CustomButton.setMaximumSize(new java.awt.Dimension(310, 310));
        CustomButton.setMinimumSize(new java.awt.Dimension(310, 310));
        CustomButton.setOpaque(false);
        CustomButton.setPreferredSize(new java.awt.Dimension(310, 310));
        CustomButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CustomButtonMouseClicked(evt);
            }
        });
        CustomButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Title.setFont(new java.awt.Font("Cantarell", 1, 24)); // NOI18N
        Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Title.setText("Event 1 title");
        CustomButton.add(Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 730, 40));

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Cantarell", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Events/Rectangle 3Big.png"))); // NOI18N
        CustomButton.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 750, 85));

        Image.setBackground(new java.awt.Color(255, 255, 255));
        Image.setForeground(new java.awt.Color(255, 255, 255));
        Image.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/DetailsIcons/4.jpeg"))); // NOI18N
        Image.setToolTipText("");
        Image.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        CustomButton.add(Image, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 750, 240));

        ButtonParent.add(CustomButton);

        CustomButton1.setBackground(new java.awt.Color(255, 255, 255));
        CustomButton1.setForeground(new java.awt.Color(255, 255, 255));
        CustomButton1.setAlignmentX(1.0F);
        CustomButton1.setAlignmentY(1.0F);
        CustomButton1.setMaximumSize(new java.awt.Dimension(310, 310));
        CustomButton1.setMinimumSize(new java.awt.Dimension(310, 310));
        CustomButton1.setOpaque(false);
        CustomButton1.setPreferredSize(new java.awt.Dimension(310, 310));
        CustomButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CustomButton1MouseClicked(evt);
            }
        });
        CustomButton1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Title1.setFont(new java.awt.Font("Cantarell", 1, 24)); // NOI18N
        Title1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Title1.setText("Event 1 title");
        CustomButton1.add(Title1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 730, 40));

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Cantarell", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Events/Rectangle 3Big.png"))); // NOI18N
        CustomButton1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 750, 85));

        Image1.setBackground(new java.awt.Color(255, 255, 255));
        Image1.setForeground(new java.awt.Color(255, 255, 255));
        Image1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Image1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/DetailsIcons/5.jpeg"))); // NOI18N
        Image1.setToolTipText("");
        Image1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        CustomButton1.add(Image1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 750, 240));

        ButtonParent.add(CustomButton1);

        CustomButton2.setBackground(new java.awt.Color(255, 255, 255));
        CustomButton2.setForeground(new java.awt.Color(255, 255, 255));
        CustomButton2.setAlignmentX(1.0F);
        CustomButton2.setAlignmentY(1.0F);
        CustomButton2.setMaximumSize(new java.awt.Dimension(310, 310));
        CustomButton2.setMinimumSize(new java.awt.Dimension(310, 310));
        CustomButton2.setOpaque(false);
        CustomButton2.setPreferredSize(new java.awt.Dimension(310, 310));
        CustomButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CustomButton2MouseClicked(evt);
            }
        });
        CustomButton2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Title2.setFont(new java.awt.Font("Cantarell", 1, 24)); // NOI18N
        Title2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Title2.setText("Event 2 title");
        CustomButton2.add(Title2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 730, 40));

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Cantarell", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Events/Rectangle 3Big.png"))); // NOI18N
        CustomButton2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 750, 85));

        Image2.setBackground(new java.awt.Color(255, 255, 255));
        Image2.setForeground(new java.awt.Color(255, 255, 255));
        Image2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Image2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/DetailsIcons/6.jpeg"))); // NOI18N
        Image2.setToolTipText("");
        Image2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        CustomButton2.add(Image2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 750, 240));

        ButtonParent.add(CustomButton2);

        CustomButton3.setBackground(new java.awt.Color(255, 255, 255));
        CustomButton3.setForeground(new java.awt.Color(255, 255, 255));
        CustomButton3.setAlignmentX(1.0F);
        CustomButton3.setAlignmentY(1.0F);
        CustomButton3.setMaximumSize(new java.awt.Dimension(310, 310));
        CustomButton3.setMinimumSize(new java.awt.Dimension(310, 310));
        CustomButton3.setOpaque(false);
        CustomButton3.setPreferredSize(new java.awt.Dimension(310, 310));
        CustomButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CustomButton3MouseClicked(evt);
            }
        });
        CustomButton3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Title3.setFont(new java.awt.Font("Cantarell", 1, 24)); // NOI18N
        Title3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Title3.setText("Event 1 title");
        CustomButton3.add(Title3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 730, 40));

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setFont(new java.awt.Font("Cantarell", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Events/Rectangle 3Big.png"))); // NOI18N
        CustomButton3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 750, 85));

        Image3.setBackground(new java.awt.Color(255, 255, 255));
        Image3.setForeground(new java.awt.Color(255, 255, 255));
        Image3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Image3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Events/RectangleMuseum.png"))); // NOI18N
        Image3.setToolTipText("");
        Image3.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        CustomButton3.add(Image3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 750, 240));

        ButtonParent.add(CustomButton3);
*/
        
        jScrollPane1.setViewportView(ButtonParent);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 840, 680));

        jLabel1.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Signing/Rectangle 3 (1).png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 940, 820));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
        Backend.EventsPage.Instance().backButtom(this,new Explore() );
    }//GEN-LAST:event_BackActionPerformed

    private void jTextField1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1FocusGained
        jTextField1.setText("");
    }//GEN-LAST:event_jTextField1FocusGained

    private void Search1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Search1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Search1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Events.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Events.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Events.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Events.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Events().setVisible(true);
            }
        });
    }

    
    // Variables declaration - do not modify                     
    private javax.swing.JButton Back;
    private javax.swing.JPanel ButtonParent;
    private javax.swing.JLabel SUbTitle;
    private javax.swing.JButton Search1;
    public static javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel jLabel1;

    /*private javax.swing.JPanel CustomButton;
    private javax.swing.JPanel CustomButton1;
    private javax.swing.JPanel CustomButton2;
    private javax.swing.JPanel CustomButton3;
    private javax.swing.JLabel Image;
    private javax.swing.JLabel Image1;
    private javax.swing.JLabel Image2;
    private javax.swing.JLabel Image3;
    private javax.swing.JLabel Title;
    private javax.swing.JLabel Title1;
    private javax.swing.JLabel Title2;
    private javax.swing.JLabel Title3;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;// End of variables declaration */                    
}

