/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import javax.swing.JButton;

/**
 *
 * @author bethoveen
 */
public class Explore extends javax.swing.JFrame {

    /**
     * Creates new form SignUpForm
     */
    public Explore() {
        initComponents();
        GUIManager.Instance().setDynamicSize(this,jPanel1);  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Title = new javax.swing.JLabel();
        SUbTitle = new javax.swing.JLabel();
        BackButton = new javax.swing.JButton();
        Visit = new javax.swing.JButton();
        Visit1 = new javax.swing.JButton();
        Visit2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        Paintings = new javax.swing.JButton();
        Ministatus = new javax.swing.JButton();
        Monuments = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1080, 920));
        setUndecorated(true);
        setSize(new java.awt.Dimension(1100, 1300));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Title.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        Title.setForeground(new java.awt.Color(153, 153, 153));
        Title.setText("All categories");
        Title.setIconTextGap(15);
        jPanel1.add(Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, 120, 50));

        SUbTitle.setFont(new java.awt.Font("Cantarell Extra Bold", 0, 36)); // NOI18N
        SUbTitle.setForeground(new java.awt.Color(153, 153, 153));
        SUbTitle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Signing/pharaoh (1).png"))); // NOI18N
        SUbTitle.setText("Explore");
        SUbTitle.setIconTextGap(15);
        jPanel1.add(SUbTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 210, 50));

        BackButton.setBackground(new java.awt.Color(0, 0, 0));
        BackButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Signing/ExploreIocns/Picture_1.png"))); // NOI18N
        BackButton.setBorder(null);
        BackButton.setBorderPainted(false);
        BackButton.setContentAreaFilled(false);
        BackButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackButtonMouseClicked(evt);
            }
        });
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });
        jPanel1.add(BackButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 50, 60));

        Visit.setBackground(new java.awt.Color(0, 0, 0));
        Visit.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        Visit.setForeground(new java.awt.Color(226, 226, 226));
        Visit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Signing/ExploreIocns/Picture_2.png"))); // NOI18N
        Visit.setText("Book An event");
        Visit.setToolTipText("book an event");
        Visit.setBorder(null);
        Visit.setBorderPainted(false);
        Visit.setContentAreaFilled(false);
        Visit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Visit.setIconTextGap(5);
        Visit.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        Visit.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Visit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VisitMouseClicked(evt);
            }
        });
        Visit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VisitActionPerformed(evt);
            }
        });
        jPanel1.add(Visit, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 30, 130, 90));

        Visit1.setBackground(new java.awt.Color(0, 0, 0));
        Visit1.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        Visit1.setForeground(new java.awt.Color(226, 226, 226));
        Visit1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Signing/ExploreIocns/Picture_2.png"))); // NOI18N
        Visit1.setText("Book A visit");
        Visit1.setToolTipText("book an event");
        Visit1.setBorder(null);
        Visit1.setBorderPainted(false);
        Visit1.setContentAreaFilled(false);
        Visit1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Visit1.setIconTextGap(5);
        Visit1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        Visit1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Visit1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Visit1MouseClicked(evt);
            }
        });
        Visit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Visit1ActionPerformed(evt);
            }
        });
        jPanel1.add(Visit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 30, 130, 90));

        Visit2.setBackground(new java.awt.Color(0, 0, 0));
        Visit2.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        Visit2.setForeground(new java.awt.Color(226, 226, 226));
        Visit2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Signing/ExploreIocns/Picturemenu_2.png"))); // NOI18N
        Visit2.setText("View Map");
        Visit2.setToolTipText("book an event");
        Visit2.setBorder(null);
        Visit2.setBorderPainted(false);
        Visit2.setContentAreaFilled(false);
        Visit2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Visit2.setIconTextGap(5);
        Visit2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        Visit2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Visit2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Visit2MouseClicked(evt);
            }
        });
        Visit2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Visit2ActionPerformed(evt);
            }
        });
        jPanel1.add(Visit2, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 30, 120, 90));

        jPanel2.setLayout(new java.awt.GridLayout(0, 1, 0, 20));

        Paintings.setBackground(new java.awt.Color(63, 218, 155));
        Paintings.setFont(new java.awt.Font("Cantarell", 1, 48)); // NOI18N
        Paintings.setForeground(new java.awt.Color(255, 255, 255));
        Paintings.setText("Historic painitng");
        Paintings.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PaintingsMouseClicked(evt);
            }
        });
        Paintings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PaintingsActionPerformed(evt);
            }
        });
        jPanel2.add(Paintings);

        Ministatus.setBackground(new java.awt.Color(63, 218, 155));
        Ministatus.setFont(new java.awt.Font("Cantarell", 1, 48)); // NOI18N
        Ministatus.setForeground(new java.awt.Color(255, 255, 255));
        Ministatus.setText("Mini Status");
        Ministatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MinistatusActionPerformed(evt);
            }
        });
        jPanel2.add(Ministatus);

        Monuments.setBackground(new java.awt.Color(63, 218, 155));
        Monuments.setFont(new java.awt.Font("Cantarell", 1, 48)); // NOI18N
        Monuments.setForeground(new java.awt.Color(255, 255, 255));
        Monuments.setText("Monuments");
        Monuments.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MonumentsMouseClicked(evt);
            }
        });
        Monuments.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MonumentsActionPerformed(evt);
            }
        });
        jPanel2.add(Monuments);

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 820, 660));

        jLabel1.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Signing/Rectangle 3 (1).png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 940, 820));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PaintingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PaintingsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PaintingsActionPerformed

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BackButtonActionPerformed

    private void VisitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VisitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VisitActionPerformed

    private void Visit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Visit1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Visit1ActionPerformed

    private void Visit2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Visit2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Visit2ActionPerformed

    private void BackButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackButtonMouseClicked
        // TODO add your handling code here:
        Backend.ExplorePage.Instance().signOutButtom(this, new SignUpForm());
    }//GEN-LAST:event_BackButtonMouseClicked

    private void Visit1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Visit1MouseClicked
        // TODO add your handling code here:
        Backend.ExplorePage.Instance().bookButtom(this, new TicketBooking());
    }//GEN-LAST:event_Visit1MouseClicked

    private void VisitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VisitMouseClicked
        // TODO add your handling code here:
        Backend.ExplorePage.Instance().eventsButtom(this, new Events());
    }//GEN-LAST:event_VisitMouseClicked

    private void Visit2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Visit2MouseClicked
        // TODO add your handling code here:
        Backend.ExplorePage.Instance().bookButtom(this, new Map());
    }//GEN-LAST:event_Visit2MouseClicked

    private void MinistatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MinistatusActionPerformed
        // TODO add your handling code here:
        Backend.ExplorePage.Instance().miniSatusPanel(this , new Category());
    }//GEN-LAST:event_MinistatusActionPerformed

    private void MonumentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MonumentsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MonumentsActionPerformed

    private void MonumentsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MonumentsMouseClicked
        // TODO add your handling code here:
         Backend.ExplorePage.Instance().monumentsPanel(this, new Category());
    }//GEN-LAST:event_MonumentsMouseClicked

    private void PaintingsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PaintingsMouseClicked
        // TODO add your handling code here:
        Backend.ExplorePage.Instance().historicPaintingsPanel(this, new Category());
    }//GEN-LAST:event_PaintingsMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Explore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Explore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Explore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Explore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Explore().setVisible(true);
            }
        });
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JButton Ministatus;
    private javax.swing.JButton Monuments;
    private javax.swing.JButton Paintings;
    private javax.swing.JLabel SUbTitle;
    private javax.swing.JLabel Title;
    private javax.swing.JButton Visit;
    private javax.swing.JButton Visit1;
    private javax.swing.JButton Visit2;
    private javax.swing.JLabel jLabel1;
    public static javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
