/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package GUI;

import javax.swing.ComboBoxModel;

/**
 *
 * @author Dina
 */
public class SignUp extends javax.swing.JFrame {

    /** Creates new form SignUp */
    public SignUp() {
        initComponents();
        GUIManager.Instance().setDynamicSize(this, jPanel1);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Subtitle = new javax.swing.JLabel();
        Icon = new javax.swing.JLabel();
        UserName = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        Icon1 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        Icon2 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        RepeatPassword = new javax.swing.JPasswordField();
        Password = new javax.swing.JPasswordField();
        Phone = new javax.swing.JTextField();
        Icon7 = new javax.swing.JLabel();
        Icon8 = new javax.swing.JLabel();
        State = new javax.swing.JComboBox<>();
        Gender = new javax.swing.JComboBox<>();
        jSeparator6 = new javax.swing.JSeparator();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        error_msg = new javax.swing.JLabel();
        Email = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        Icon9 = new javax.swing.JLabel();
        Icon10 = new javax.swing.JLabel();
        NId = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        Icon11 = new javax.swing.JLabel();
        Age = new javax.swing.JTextField();
        jSeparator9 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setPreferredSize(new java.awt.Dimension(1000, 820));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Subtitle.setFont(new java.awt.Font("Calibri", 0, 30)); // NOI18N
        Subtitle.setForeground(new java.awt.Color(153, 153, 153));
        Subtitle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Icons/SignUp/pharaoh.png"))); // NOI18N
        Subtitle.setText(" Let's Introduce ");
        jPanel1.add(Subtitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 410, 70));

        Icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Icons/SignUp/Icon.png"))); // NOI18N
        jPanel1.add(Icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 60, 60));

        UserName.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        UserName.setForeground(new java.awt.Color(153, 153, 153));
        UserName.setText("UserName");
        UserName.setToolTipText("");
        UserName.setBorder(null);
        UserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserNameActionPerformed(evt);
            }
        });
        jPanel1.add(UserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 630, 40));

        jSeparator1.setBackground(new java.awt.Color(160, 160, 160));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 740, 10));

        Icon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Icons/SignUp/Passwordpass.png"))); // NOI18N
        jPanel1.add(Icon1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, -1, -1));

        jSeparator2.setBackground(new java.awt.Color(153, 153, 153));
        jSeparator2.setForeground(new java.awt.Color(153, 153, 153));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, 740, 30));

        Icon2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Icons/SignUp/Passwordpass.png"))); // NOI18N
        jPanel1.add(Icon2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, -1, -1));

        jSeparator3.setBackground(new java.awt.Color(153, 153, 153));
        jSeparator3.setForeground(new java.awt.Color(153, 153, 153));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 300, 740, 30));

        RepeatPassword.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        RepeatPassword.setForeground(new java.awt.Color(153, 153, 153));
        RepeatPassword.setText("jPasswordField1");
        RepeatPassword.setBorder(null);
        RepeatPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RepeatPasswordActionPerformed(evt);
            }
        });
        jPanel1.add(RepeatPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, 630, 30));

        Password.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        Password.setForeground(new java.awt.Color(153, 153, 153));
        Password.setText("jPasswordField1");
        Password.setBorder(null);
        Password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordActionPerformed(evt);
            }
        });
        jPanel1.add(Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 630, 30));

        Phone.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        Phone.setForeground(new java.awt.Color(153, 153, 153));
        Phone.setText("Phone Number");
        Phone.setToolTipText("");
        Phone.setBorder(null);
        Phone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PhoneActionPerformed(evt);
            }
        });
        jPanel1.add(Phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 320, 630, 40));

        Icon7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Icons/SignUp/Icon.png"))); // NOI18N
        jPanel1.add(Icon7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 60, 60));

        Icon8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Icons/SignUp/Eye (closed)eye.png"))); // NOI18N
        jPanel1.add(Icon8, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 190, 60, 60));

        State.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        State.setForeground(new java.awt.Color(153, 153, 153));
        State.setMaximumRowCount(3);
        State.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "State", "Student", "Employee", "Tourist", " " }));
        State.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        State.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StateActionPerformed(evt);
            }
        });
        jPanel1.add(State, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 560, 180, 40));

        Gender.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        Gender.setForeground(new java.awt.Color(153, 153, 153));
        Gender.setMaximumRowCount(3);
        Gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gender", "Male", "Female", "Rather Not say", " ", " " }));
        Gender.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Gender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenderActionPerformed(evt);
            }
        });
        jPanel1.add(Gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 560, 180, 40));

        jSeparator6.setBackground(new java.awt.Color(160, 160, 160));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 360, 740, 10));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Icons/SignUp/Prev_Button.png"))); // NOI18N
        jButton2.setBorder(null);
        jButton2.setContentAreaFilled(false);
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 670, 80, 100));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Icons/SignUp/Next_Button.png"))); // NOI18N
        jButton3.setBorder(null);
        jButton3.setContentAreaFilled(false);
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 670, 530, 100));

        error_msg.setFont(new java.awt.Font("Calibri", 0, 13)); // NOI18N
        error_msg.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(error_msg, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 610, 370, 60));

        Email.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        Email.setForeground(new java.awt.Color(153, 153, 153));
        Email.setText("Email");
        Email.setToolTipText("");
        Email.setBorder(null);
        Email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailActionPerformed(evt);
            }
        });
        jPanel1.add(Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 380, 630, 40));

        jSeparator7.setBackground(new java.awt.Color(160, 160, 160));
        jPanel1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 420, 740, 10));

        Icon9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Icons/SignUp/Icon.png"))); // NOI18N
        jPanel1.add(Icon9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, 60, 60));

        Icon10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Icons/SignUp/Icon.png"))); // NOI18N
        jPanel1.add(Icon10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 430, 60, 60));

        NId.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        NId.setForeground(new java.awt.Color(153, 153, 153));
        NId.setText("National ID");
        NId.setToolTipText("");
        NId.setBorder(null);
        NId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NIdActionPerformed(evt);
            }
        });
        jPanel1.add(NId, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 440, 630, 40));

        jSeparator8.setBackground(new java.awt.Color(160, 160, 160));
        jPanel1.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 480, 740, 10));

        Icon11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Icons/SignUp/Icon.png"))); // NOI18N
        jPanel1.add(Icon11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 490, 60, 60));

        Age.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        Age.setForeground(new java.awt.Color(153, 153, 153));
        Age.setText("Age");
        Age.setToolTipText("");
        Age.setBorder(null);
        Age.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgeActionPerformed(evt);
            }
        });
        jPanel1.add(Age, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 500, 90, 40));

        jSeparator9.setBackground(new java.awt.Color(160, 160, 160));
        jPanel1.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 540, 220, 10));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Icons/SignUp/BG.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 964, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PhoneActionPerformed

    private void PasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordActionPerformed

    private void RepeatPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RepeatPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RepeatPasswordActionPerformed

    private void UserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UserNameActionPerformed

    private void StateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StateActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
        
        Backend.SignUpPage.Instance().toNextPage(
                this,
                new Explore(),
                
                Backend.SignUpPage.Instance().insertDataOfNewAccount(
                        UserName,
                        NId,
                        Phone,
                        Password,
                        Email,
                        Age,
                        Gender,State));
    }//GEN-LAST:event_jButton3MouseClicked

    private void GenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GenderActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
       Backend.SignUpPage.Instance().backButtom(
                this,
               new SignUpForm());
               
               
                
    }//GEN-LAST:event_jButton2MouseClicked

    private void EmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmailActionPerformed

    private void NIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NIdActionPerformed

    private void AgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AgeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Age;
    private javax.swing.JTextField Email;
    private javax.swing.JComboBox<String> Gender;
    private javax.swing.JLabel Icon;
    private javax.swing.JLabel Icon1;
    private javax.swing.JLabel Icon10;
    private javax.swing.JLabel Icon11;
    private javax.swing.JLabel Icon2;
    private javax.swing.JLabel Icon7;
    private javax.swing.JLabel Icon8;
    private javax.swing.JLabel Icon9;
    private javax.swing.JTextField NId;
    private javax.swing.JPasswordField Password;
    private javax.swing.JTextField Phone;
    private javax.swing.JPasswordField RepeatPassword;
    private javax.swing.JComboBox<String> State;
    private javax.swing.JLabel Subtitle;
    private javax.swing.JTextField UserName;
    private javax.swing.JLabel error_msg;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    // End of variables declaration//GEN-END:variables

}
